

// TODO
const FIRST_FLOOR = [
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'FITT', 'FITT', 'FITT', 'FITT', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'FITT', 'FITT', 'FITT', 'FITT', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'MCAF', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'MCAF', 'MCAF', 'PATH', 'MCAF', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'WALL', 'MCAF', 'MCAF', 'PATH', 'MCAF', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'MCAF', 'MCAF', 'PATH', 'MCAF', 'WALL', 'WALL', 'STAI', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'CLAS', 'CLAS', 'CLAS', 'PATH', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'CLAS', 'CLAS', 'WALL', 'PATH', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'STAI', 'STAI' ],
[ 'CLAS', 'CLAS', 'PATH', 'PATH', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'OUTD' ],
[ 'CLAS', 'CLAS', 'WALL', 'WALL', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'COMM', 'WALL', 'BAND', 'BAND', 'BAND', 'BAND', 'BAND', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'CLAS', 'CLAS' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'COMM', 'WALL', 'BAND', 'BAND', 'BAND', 'BAND', 'BAND', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'CLAS', 'CLAS' ], 
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'HGYM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'COMM', 'WALL', 'BAND', 'BAND', 'BAND', 'BAND', 'BAND', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'COMM', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'CLAS', 'CLAS' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'COMM', 'WALL', 'LGI ', 'LGI ', 'LGI ', 'LGI ', 'PATH', 'PATH', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'STAI', 'STAI', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'COMM', 'WALL', 'LGI ', 'LGI ', 'LGI ', 'LGI ', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'CLAS', 'CLAS' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'COMM', 'WALL', 'LGI ', 'LGI ', 'LGI ', 'LGI ', 'WALL', 'CLAS', 'WALL', 'CLAS', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL' ],
[ 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'WALL', 'WALL', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'WALL', 'WALL', 'PATH', 'COMM', 'WALL', 'LGI ', 'LGI ', 'LGI ', 'LGI ', 'WALL', 'CLAS', 'WALL', 'CLAS', 'WALL', 'PATH', 'WALL', 'CLAS', 'CLAS' ],
[ 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'WALL', 'WALL', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'WALL', 'CLAS', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'PATH', 'WALL', 'PATH', 'WALL', 'PATH', 'WALL', 'PATH', 'WALL' ],  
[ 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'WALL', 'WALL', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'WALL', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'STAI' ],
[ 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'WALL', 'WALL', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'WALL', 'WALL', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'WALL', 'WALL', 'WALL', 'PATH', 'STAI', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ], 
[ 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'MGYM', 'WALL', 'WALL', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'LIBR', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'NURS', 'NURS', 'NURS', 'WALL', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'WALL', 'STAG', 'STAG' ],
[ 'PATH', 'PATH', 'PATH', 'PATH', 'WALL', 'CLAS', 'CLAS', 'CLAS', 'WALL', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'WALL', 'STAG', 'STAG' ],
[ 'WALL', 'WALL', 'WALL', 'PATH', 'WALL', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'AUDI', 'WALL', 'STAG', 'STAG' ],
[ 'CLAS', 'CLAS', 'WALL', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'PATH', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'CLAS', 'CLAS', 'PATH', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'PATH', 'PATH', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ],
[ 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'OUTD', 'OUTD', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL', 'WALL' ]
];


module.exports = FIRST_FLOOR;